[package]
name = "mm-web-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
metamath-knife = { path = "../metamath-knife" }
actix-web = "3.3"
itertools = "0.10"
